### ISSUE TITLE
How do I get this file,CelebA_aligned_reduced.h5?

### ISSUE THREAD

**Issue by elggurts22** [a514514772/Pytorch-VAE-GAN#3]

**Comment by hui-po-wang** [comment]
https://drive.google.com/file/d/0B512lwbc5_ZFbmxIWkZ1dDlFckE/view?usp=sharing

**Comment by elggurts22** [comment]
@a514514772 Thank you very much！

**Comment by wizofe** [comment]
File not there anymore :(

**Comment by astroartisan** [comment]
Looking for the .h5 file
